
# Site settings
email: zhangyuanxin@foxmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:
baidu_analytics: true
repo: http://github.com/zhangyuanxin/blog-jekyll

# SEO settings
title: 斯是陋室
description: 
url: http://uiplus.org
twitter_username: 
default_img: 

# Profile settings
name: 张远馨
profile_img: http://uiplus.org/assets/images/avatar.jpg
profile: 山东人，生于1991年，毕业于山东中医药大学，现居山东济南，就职于济南雷恩信息科技有限公司研发部，始于中软国际科技有限公司。业余微信公众号玩家、业余简书玩家，爱好电影、音乐，喜欢散步。
social:
  github: http://github.com/zhangyuanxin
  codepen: http://codepen.io/thomasvaeth/
  linkedin: http://linkedin.com/in/zhangyuanxin
  twitter: https://twitter.com/thomasvaeth
  facebook: https://www.facebook.com/zhangyuanxin
  instagram: https://www.instagram.com/zhangyuanxin/

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
