
# Site settings
email: zhangyuanxin@foxmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:
baidu_analytics: true
repo: http://github.com/zhangyuanxin/blog-jekyll

# SEO settings
title: 斯是陋室
description: 讀書、寫作、攝影
url: http://uiplus.org
twitter_username: zhangyuanxin
default_img: http://uiplus.org/assets/images/avatar.jpg

# Profile settings
name: 張遠馨
profile_img: http://uiplus.org/assets/images/avatar.jpg
profile: 張遠馨         生於壹玖玖壹年冬，山東人，肄業于山東中醫藥大學，今居濟南歷下區，現就職于濟南雷恩信息科技有限公司技術研發部門，曾就職于中軟國際科技服務有限公司。業餘時間喜歡看看電影、聽歌賞樂、翻閲科技新聞，現經營一個靜思詩文的微信公衆號，沒事在簡書上寫寫文章。
social:
  github: http://github.com/zhangyuanxin
#  codepen: http://codepen.io/zhangyuanxin
  linkedin: http://www.linkedin.com/in/%E8%BF%9C%E9%A6%A8-%E5%BC%A0-449081101
#  twitter: https://twitter.com/zhangyuanxin
#  facebook: https://www.facebook.com/zhangyuanxin
#  instagram: https://www.instagram.com/zhangyuanxin

page:
  previous: 前一頁
  next: 后一頁
  back: 書文
  post: 書文
  category: 分類
  readmore: 閲讀原文
  readnext: 繼續閲讀
  viewall: 展開全部
  archive: 全部

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
pygments: true
source: ./
destination: ./_site
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
